name: 导出 FlowThread 评论
on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 签出
              uses: actions/checkout@v4
            - name: 设置 node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
            - name: 安装 npm 依赖
              run: npm install
            - name: 配置 git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git pull --rebase
            - name: 导出 FlowThread 评论
              env:
                  MOEGIRL_UK_MGPUSERID: ${{ vars.MOEGIRL_UK_MGPUSERID }}
                  MOEGIRL_UK_MGPTOKEN: ${{ secrets.MOEGIRL_UK_MGPTOKEN }}
              run: node scripts/导出FlowThread评论
            - name: 更新 flowthread.json
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git add -f flowthread.json
                  if ! git diff-index --quiet HEAD --; then
                      git commit -m "Update threeds"
                      git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gui-ying233/JustMoeComments.git
                  else
                      echo "评论无更新"
                  fi
